### PR TITLE
feature-request:preserve whitespace

### LINKED ISSUE #26: preserve whitespace in layouts

### PR DESCRIPTION
**Pull request by tjbenton**
This fixes #26. It updates it to output the expected result in #25 
#### Expected

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>test</title>
  </head>
  <body>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
    <ul>
      <li>item</li>
      <li>item</li>
      <li>item</li>
      <li>item</li>
    </ul>    
    <h1>Partial</h1>
  </body>
</html>
```

### CODE REVIEW

**Comment by tjbenton** [comment]
it might not be the most elegant solution but it seems to be working for me. I also fixed some eslint errors that happened when I ran `gulp lint`.

**Comment by jonschlinkert** [comment]
it looks great! thanks! This seems like a great feature to have directly in the `layouts` library. What are your thoughts on moving the code there? @tjbenton (cc @doowb)?

**Comment by doowb** [comment]
@tjbenton I agree with @jonschlinkert that this should be in the `layouts` library.

I like that you loop over the stack to calculate the indentation correctly when a view has nested layouts, but I think that also needs to be done in the `layouts` library and only for layouts that are being applied. The change you have will apply too much indentation because it will loop over all of the layouts.

**Comment by tjbenton** [comment]
@doowb @jonschlinkert I updated this to work with the [layouts pr](https://github.com/doowb/layouts/pull/5) that I opened. I got it working for the test cases we are looking into but there were breaking changes made in `layouts` that hadn't been updated in `templates` yet so I updated as much as a could. However there're 6 test cases that are failing that I can't seem to figure out and I was hoping you guys could take a look at them since you're more familiar with this codebase.

**Comment by doowb** [comment]
@tjbenton thanks for updating this. I'll take a look at this soon.

**Comment by jonschlinkert** [comment]
closing since this request was moved to the layouts library. I also think this is a bad idea since it will have unintended consequences, like adding leading whitespace to `<pre>` tags that happen to be in the string.

**Pull request closed without merging**
